### ISSUE TITLE
Add Watchlist Functionality

### ISSUE THREAD

**Issue by vijaychoudhary33** [vijaychoudhary33/movieblazer#7]
Following Steps are take to complete Watchlist 

1. Database setup: the necessary tables and associations in your database.
2. Model Associations: associations between the models.
3. Routes and Controller Actions: Set up the routes and controller actions for managing the watchlist
4. Views: Create the necessary views to display the watchlist.

**Comment by mandalorian99** [comment]
1.  what is watchlist feature ? 
       short description . 
       
2. Do you have any database schema ? put your db schema here or migration you  have creaated . 

i think these two are enough to start ..

please start on building this feautre .

**Comment by vijaychoudhary33** [comment]
```
  create_table :watchlists do |t|
      t.references :user, null: false, foreign_key: true
      t.string :name
      t.string :visibility
```
```
class CreateWatchlistsItems < ActiveRecord::Migration[7.0]
  def change
    create_table :watchlists_items do |t|
      t.references :watchlist, null: false, foreign_key: true
      t.references :movie, null: false, foreign_key: true

      t.timestamps
    end
  end
end

```
